# Generated by Django 3.2.9 on 2021-12-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('python', 'PYTHON'), ('.net', 'DOT_NET')], max_length=255, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('intern', 'INTERN'), ('junior', 'JUNIOR'), ('middle', 'MIDDLE'), ('senior', 'SENIOR'), ('team lead', 'TEAM_LEAD')], max_length=255, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_text', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('python', 'PYTHON'), ('.net', 'DOT_NET')], max_length=255, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('intern', 'INTERN'), ('junior', 'JUNIOR'), ('middle', 'MIDDLE'), ('senior', 'SENIOR'), ('team lead', 'TEAM_LEAD')], max_length=255, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=512, null=True)),
                ('full_description', models.CharField(blank=True, max_length=512, null=True)),
                ('requirements', models.CharField(blank=True, max_length=512, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=512, null=True)),
                ('bonuses', models.CharField(blank=True, max_length=512, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
